# Generated by Django 4.2.4 on 2023-08-17 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='upload',
            field=models.FileField(default='upload', upload_to='uploads/'),
        ),
    ]
